from DiGraph import *
from GraphAlgo import GraphAlgo

if __name__ == '__main__':
    # algo = GraphAlgo()
    # algo.load_from_json('../data/A0.json')
    # print(algo.is_connected())
    # algo.plot_graph()
    # algo.load_from_json('../data/A1.json')
    # print(algo.is_connected())
    # algo.plot_graph()
    # algo.load_from_json('../data/A2.json')
    # print(algo.is_connected())
    # algo.plot_graph()
    # algo.load_from_json('../data/A3.json')
    # print(algo.is_connected())
    # algo.plot_graph()
    # algo.load_from_json('../data/A4.json')
    # print(algo.is_connected())
    # algo.plot_graph()
    g = DiGraph()
    g.add_node(1)
    g.add_node(2)
    g.add_node(3)
    g.add_node(4)
    g.add_node(5)
    g.add_edge(1, 2, 2)
    g.add_edge(2, 3, 2)
    g.add_edge(3, 4, 2)
    g.add_edge(4, 5, 2)
    g.add_edge(1, 3, 2)
    algo = GraphAlgo(g)
    list = [5, 1, 2, 4]
    print(algo.TSP(list))
